spring: 
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        # https://stackoverflow.com/questions/26548505/org-hibernate-hibernateexception-access-to-dialectresolutioninfo-cannot-be-null
        # https://stackoverflow.com/a/66778396/13723015
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2dll:
          create_namespaces: true

  datasource:
    url: jdbc:mysql://${DB_HOST:comment-api-mysql}:${DB_PORT:3306}/${DB_NAME:dev}?createDatabaseIfNotExist=true
    username: ${DB_USER:mysql}
    password: ${DB_PASSWORD:thisIsReallyStrongPassword123}
    driver-class-name: com.mysql.cj.jdbc.Driver
