apiVersion: apps/v1
kind: Deployment
metadata:
  name: author-api-depl
spec:
  replicas: 1
  # selecting a container from template
  selector:
    matchLabels:
      app: authorapiservice
  # defining a container
  template:
    metadata:
      labels:
        app: authorapiservice
    spec:
      containers:
        - name: authorapiservice
          image: testcontainerregistrymyfirstrg9554fd8774bb485c878d.azurecr.io/authorserviceimagerepo
          env:
            - name: PORT
              value: "80"
            - name: RABBIT_MQ_HOST
              value: rabbitmq-clusterip-srv
            - name: RABBIT_MQ_PASSWORD
              value: rabbitmq
            - name: RABBIT_MQ_USERNAME
              value: rabbitmq
            - name: DB_HOST
              value: author-api-mysql-clusterip-srv
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: dev
            - name: DB_USER
              value: mysql
            - name: DB_PASSWORD
              value: thisIsReallyStrongPassword123

---
apiVersion: v1
kind: Service
metadata:
  name: author-service
spec:
  type: ClusterIP
  selector:
    app: authorapiservice
  ports:
    - name: authorsrvpt
      protocol: TCP
      port: 80
      targetPort: 80
