apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-api-depl
spec:
  replicas: 1
  # selecting a container from template
  selector:
    matchLabels:
      app: bookapiservice
  # defining a container
  template:
    metadata:
      labels:
        app: bookapiservice
    spec:
      containers:
        - name: bookapiservice
          image: testcontainerregistrymyfirstrgb6bce5d44706469baf6b.azurecr.io/authorserviceimagerepo
          env:
            - name: PORT
              value: "80"
            - name: RABBIT_MQ_HOST
              value: rabbitmq-clusterip-srv
            - name: RABBIT_MQ_PASSWORD
              value: rabbitmq
            - name: RABBIT_MQ_USERNAME
              value: rabbitmq
            - name: DB_HOST
              value: book-api-mysql-clusterip-srv
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: dev
            - name: DB_USER
              value: mysql
            - name: DB_PASSWORD
              value: thisIsReallyStrongPassword123

---
apiVersion: v1
kind: Service
metadata:
  name: book-service
spec:
  type: ClusterIP
  selector:
    app: bookapiservice
  ports:
    - name:  booksrvpt
      protocol: TCP
      port: 80
      targetPort: 80
